image:
  repository: spehlivan/elchi
  tag: v0.1.0
  pullPolicy: IfNotPresent

replicas: 3

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "300m"

service:
  type: ClusterIP
  port: 80

