{{- if .Values.global.selfServiceMongo }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
{{- end }} 