apiVersion: v1
kind: Service
metadata:
  name: elchi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: elchi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: elchi