replicaCount: 1
image:
  repository: mongo
  tag: 6.0.12
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

persistence:
  enabled: true
  size: 1Gi
  storageClass: local-path

service:
  type: ClusterIP
  port: 27017
