apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 1989
      protocol: TCP
      name: http
    - port: 9901
      targetPort: 9901
      protocol: TCP
      name: admin
  selector:
    app: envoy