{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: 1989
      nodePort: {{ .Values.service.httpPort }}
    - name: admin
      port: 9901
      targetPort: 9901
      nodePort: {{ .Values.service.adminPort }}
  selector:
    app: envoy
{{- end }} 